nome = str(input('Digite o seu nome: ')).strip()
n = nome.split()
print('Seu primeiro nome é: {}'.format(n[0]))
print('Seu último nome é: {}'.format(n[len(n) - 1]))
print('Email: {}.{}@domínio.com.br'.format(n[0].lower(), n[len(n) - 1]))
